replicaCount: 1
image:
  repository: rabbitmq
  tag: 3-management
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  amqp: 5672
  distPort: 25672
  managerPort: 15672

ingress:
  enabled: false
